copilot/fix-9fae47c8-9630-4ae1-90f1-4695b65c0227
# SwiftLint configuration for AcoustiScan project
# Reference: https://github.com/realm/SwiftLint

# Paths to include and exclude
included:
  - Sources
  - Tests
  - RT60_014_Report_Erstellung
  - swift_coding

excluded:
  - .build
  - .git
  - .github
  - "*/Tests/Resources/*"
  - "**/*.zip"
  - AcoustiScanConsolidated/.build

# Rules to enable
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rules to disable
disabled_rules:
  - identifier_name # Too restrictive for this project
  - trailing_whitespace

# Customizable rules
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 200
  error: 350

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

# Custom rules for this project
custom_rules:
  comments_in_german:
    name: "German Comments"
    message: "Comments should be in German for this project"
    regex: '^\s*//\s*[A-Z][a-z]+.*[^äöüßÄÖÜ\s]$'
    severity: warning

  rt60_naming:
    name: "RT60 Naming Convention"
    message: "RT60 related variables should follow the naming pattern"
    regex: 'rt60.*'
    match_kinds:
      - identifier
    severity: warning

# Reporter type
reporter: "xcode"